apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  labels:
    app: golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: ludesdeveloper/github_dockerhub_heroku:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 1323
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
spec:
  selector:
    app: golang
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323
